games:
  - name: "LegendOfMortal"
    gamePath: 'C:\Program Files (x86)\Steam\steamapps\common\LegendOfMortal'
    managedPath: '\Mortal_Data\Managed'
    pluginPath: '\BepInEx\plugins'
    releasePath: '\ReleaseFolder\Files'
    export: true
    # version: 6
    version: 5
  - name: "LegendOfDragonHeir"
    gamePath: 'G:\SteamLibrary\steamapps\common\LongYinLiZhiZhuan'
    managedPath: '\BepInEx\plugins'
    pluginPath: '\BepInEx\plugins'
    releasePath: '\ReleaseFolder\Files'
    export: true
    version: 6.IL2CPP
  - name: "Wanxiang"
    gamePath: 'C:\Program Files (x86)\Steam\steamapps\common\wanxiang\wanxiang' 
    managedPath: '\WXQXZ_Data\Managed'
    pluginPath: '\BepInEx\plugins'
    releasePath: '\ReleaseFolder\Files'
    export: true
    version: 5
  - name: "NextStopJianghu2"
    gamePath: 'G:\SteamLibrary\steamapps\common\下一站江湖Ⅱ\下一站江湖Ⅱ'
    managedPath: '\下一站江湖Ⅱ_Data\Managed'
    pluginPath: '\BepInEx\plugins'
    releasePath: '\ReleaseFolder\Files'
    export: false
    version: 5